### ISSUE TITLE
🐛💻 – clean docs workflow fails because dependencies not found

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#56]
**Describe the problem**

```sh
error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
[7](https://github.com/TIDES-transit/TIDES/actions/runs/3106685214/jobs/5033875206#step:6:8)
cannot find module 'mermaid2' (No module named 'mermaid2')
[8](https://github.com/TIDES-transit/TIDES/actions/runs/3106685214/jobs/5033875206#step:6:9)
  in "mkdocs.yml", line 55, column 19
```

Looks like we need to add an install dependencies block to the clean-docs workflow:

```yaml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
```

**Steps to reproduce**
