### ISSUE TITLE
🐛💻 – Github Action Fails to Post Comment using actions/github-script@v5

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#69]
**Describe the problem**

Github Actions fails when running below code for posting a comment to PRs due to a deprecation warning (or perhaps some other bug or failure). 

**Steps to reproduce**

Run following github workflow job:

```yaml
runs-on: ubuntu-latest
    if: ${{ github.context.event_name }} == "pull_request"
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Documentation available at: [`http://tides-transit.github.io/TIDES/${{ github.ref_name }}`](http://tides-transit.github.io/TIDES/${{ github.ref_name }})'
            })
```

[GH Action Result](https://github.com/TIDES-transit/TIDES/actions/runs/3145557037/jobs/5112988115)

```sh
Run actions/github-script@v5
(node:1551) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:4561:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/TIDES-transit/TIDES/issues/62/comments',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Wed, 28 Sep 2022 17:21:34 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=3[15](https://github.com/TIDES-transit/TIDES/actions/runs/3145557037/jobs/5112988115#step:2:16)36000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3',
      'x-github-request-id': '0401:5227:43969CA:89D82[16](https://github.com/TIDES-transit/TIDES/actions/runs/3145557037/jobs/5112988115#step:2:17):6334829E',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '999',
      'x-ratelimit-reset': '1664389294',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/reference/issues#create-an-issue-comment'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/TIDES-transit/TIDES/issues/62/comments',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.5.1 Node.js/12.[22](https://github.com/TIDES-transit/TIDES/actions/runs/3145557037/jobs/5112988115#step:2:23).7 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"Documentation available at: [`[http://tides-transit.github.io/TIDES/62/merge`](http://tides-transit.github.io/TIDES/62/merge)](http://tides-transit.github.io/TIDES/62/merge%60](http://tides-transit.github.io/TIDES/62/merge))"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
Error: Unhandled error: HttpError: Resource not accessible by integration
```
